version: '3.7'

volumes:
  caddy_log:
    driver: local

services:
  node:
    image: mhart/alpine-node:11.4.0
    container_name: node
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - "../:/usr/src/app:rw"
    environment:
      PANDASCORE_API_TOKEN: ${PANDASCORE_API_TOKEN}
      GA_TRACKING_ID: ${GA_TRACKING_ID}
    restart: unless-stopped
    entrypoint: /usr/src/app/run.sh

  proxy:
    image: abiosoft/caddy
    container_name: caddy
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    volumes:
      - "../:/usr/src/app:rw"
      - "./caddy/Caddyfile:/etc/Caddyfile:rw"
      - "./caddy/.caddy:/root/.caddy:rw"
      - "caddy_log:/var/log/caddy:rw"
    depends_on:
      - node
    restart: unless-stopped
